### ISSUE TITLE
mplayer: Compiled against from ffmpeg (mplayer: error while loading shared libraries: libswscale.so.4: cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by felixbecker2** [artix-linux/packages#12]
Running `mplayer`, I get the error

    mplayer: error while loading shared libraries: libswscale.so.4: cannot open shared object file: No such file or directory

Output of `ls /usr/lib/libswscale.so*`:

    /usr/lib/libswscale.so  /usr/lib/libswscale.so.5  /usr/lib/libswscale.so.5.1.100

`world/mplayer` seems to be compiled against a wrong `ffmpeg`.

`mplayer` and `ffmpeg` are both installed from Artix Linux `world` repository (`pacman -S world/mplayer world/ffmpeg`).

I did a `pacman -Syyu` before.

`mplayer` from Arch Linux' `extra`-repository works (`pacman -S extra/mplayer`).

**Comment by konimex** [comment]
I think this is solved so I'm closing this issue. If this issue still persists with the latest `ffmpeg` and `mplayer` please reopen.
