### ISSUE TITLE
Fluidsynth depends on lash which now is in AUR (orphaned)

### ISSUE THREAD

**Issue by gCurse** [artix-linux/packages#14]
Fluidsynth should not depend on lash anymore?
See [latest arch-package change](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/fluidsynth&id=b11b56060a34ad22e6f68780e3af4fcdf1e90575)

**Comment by konimex** [comment]
fluidsynth has been moved to the packages-galaxy repo.

Closing this. If there's any more issue regaridng fluidsynth please open a new issue in the packages-galaxy repo instead.
